spring:
  application:
    name: memo
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mvc:
    view:
      prefix: /WEB-INF/jsp/   # JSP 파일 경로
      suffix: .jsp            # JSP 파일 확장자
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
